services:
  - type: web
    name: bingo
    env: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: Bingo
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: bingo
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: bingo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: bingo-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: bingo-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: bingo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: bingo-db
          property: password

databases:
  - name: bingo-db
    plan: free
    databaseName: bingo
    user: bingo
